### ISSUE TITLE
TabControl incompatibility (1.2.0)

### ISSUE THREAD

**Issue by BangL** [dojo90/NLogViewer#16]
When i smash my NLogViewer instance into the Content of a TabItem (of a TabControl),
whenever i re-open the tab, NlogViewer seems to create additional nlog-targets, and then shows all messages multiple times. increasing exponentially on each re-open.

this bug seems to be introduced in 1.2.0, i don't remember noticing this behaviour before.

maybe helpful: the Loaded event of TabItem's get called on each re-opening of that tab. This differs from the Window Loaded event behaviour

**Comment by dojo90** [comment]
Thanks for your report!

I have just fixed the issue. The problem was that the Loaded Event was fired again which results in a re-subscribing the subsciption.

This has now been stopped and a scheduling concept has been implemented.

See: https://github.com/dojo90/NLogViewer/pull/17/commits/459e2f9889f4af93e0820e14030fdccab331d1d6

**Comment by BangL** [comment]
oh well.. ok, i just tested 1.2.1 now, and nope.. the issue isn't really fixed yet.
Yes, i don't get multiplicated messages now anymore.
but now.. the control just entirely stops listening, whenever you 'leave' the tab once.

**Comment by dojo90** [comment]
You were right! The problem was the `OnVisualParentChanged()` which is also called when the `parent` has changed.

Now I implemented a logic that looks at every `unloaded` event in `LogicalTree` if  `NLogViewer` is still present or not. Depending on this the `subscription` is then disposed.

See here: https://github.com/dojo90/NLogViewer/commit/c8316bc85e2462eabfe528feb332c2e3c70cbfd3#diff-30a13f72ef66543e580cf2471fa73a9b

**Comment by BangL** [comment]
lovely.
I'm gonna check it out and test again, when i get back home.
thanks for the support. keep up the good work!

**Comment by BangL** [comment]
sorry, but it is still not fixed.
in 1.2.2 i get no log at all now.

**Comment by dojo90** [comment]
![test](https://user-images.githubusercontent.com/17551597/75230414-df93f680-57b3-11ea-9a2b-0466b15276f2.gif)

Did you test the latest version?
Please pull the master and test yourself, or create a new branch and modify the testapp so I can reproduce the error.

*You have to comment out the following lines in the `MainWindow.xaml.cs` if you want to test*

```csharp
if((_CntMessage == 10 || _CntError == 20) && TabControl1.Items.Count > 0)
    TabControl1.Items.RemoveAt(0);
```

**Comment by BangL** [comment]
fun fact: i cannot get it reproduced either. i just copied all my related code over into your testapp, where it magically just works.
while in my other project, it's still not working at all. don't see why. - freakin weird!

**Comment by BangL** [comment]
alright.
Now i've spent the whole day to port all my code from VB to C#, and that actually solved the issue for some reason.

**Comment by dojo90** [comment]
Glad you were able to fix your problem! 👍

Since I don't program VB myself, you would have to troubleshoot the problem yourself. Once you have found the bug, I can patch it in the library.
